description: |-
  Dell R720 Proxmox Server #2
prompt:
  colors:
    primary: 52
    secondary: 124
    tertiary: 102
  emoji: 🦀
pve_cluster_id: old_anchor
pve_ip_address: 10.2.0.2
pci_passthrough_ids:
  - '10de:1c82'
  - '10de:0fb9'
